// -*- truncate-lines: t; -*-

// OPTION(var, env, help)

OPTION( PrintImages,              code_PRINT_IMAGES,               "log image and library names as they are loaded")
OPTION( PrintImageTimes,          code_PRINT_IMAGE_TIMES,          "measure duration of image loading steps")
OPTION( PrintLoading,             code_PRINT_LOAD_METHODS,         "log calls to class and category +load methods")
OPTION( PrintInitializing,        code_PRINT_INITIALIZE_METHODS,   "log calls to class +initialize methods")
OPTION( PrintResolving,           code_PRINT_RESOLVED_METHODS,     "log methods created by +resolveClassMethod: and +resolveInstanceMethod:")
OPTION( PrintConnecting,          code_PRINT_CLASS_SETUP,          "log progress of class and category setup")
OPTION( PrintProtocols,           code_PRINT_PROTOCOL_SETUP,       "log progress of protocol setup")
OPTION( PrintIvars,               code_PRINT_IVAR_SETUP,           "log processing of non-fragile ivars")
OPTION( PrintVtables,             code_PRINT_VTABLE_SETUP,         "log processing of class vtables")
OPTION( PrintVtableImages,        code_PRINT_VTABLE_IMAGES,        "print vtable images showing overridden methods")
OPTION( PrintCaches,              code_PRINT_CACHE_SETUP,          "log processing of method caches")
OPTION( PrintFuture,              code_PRINT_FUTURE_CLASSES,       "log use of future classes for toll-free bridging")
OPTION( PrintGC,                  code_PRINT_GC,                   "log some GC operations")
OPTION( PrintPreopt,              code_PRINT_PREOPTIMIZATION,      "log preoptimization courtesy of dyld shared cache")
OPTION( PrintCxxCtors,            code_PRINT_CXX_CTORS,            "log calls to C++ ctors and dtors for instance variables")
OPTION( PrintExceptions,          code_PRINT_EXCEPTIONS,           "log exception handling")
OPTION( PrintExceptionThrow,      code_PRINT_EXCEPTION_THROW,      "log backtrace of every code_exception_throw()")
OPTION( PrintAltHandlers,         code_PRINT_ALT_HANDLERS,         "log processing of exception alt handlers")
OPTION( PrintReplacedMethods,     code_PRINT_REPLACED_METHODS,     "log methods replaced by category implementations")
OPTION( PrintDeprecation,         code_PRINT_DEPRECATION_WARNINGS, "warn about calls to deprecated runtime functions")
OPTION( PrintPoolHiwat,           code_PRINT_POOL_HIGHWATER,       "log high-water marks for autorelease pools")
OPTION( PrintCustomRR,            code_PRINT_CUSTOM_RR,            "log classes with un-optimized custom retain/release methods")
OPTION( PrintCustomAWZ,           code_PRINT_CUSTOM_AWZ,           "log classes with un-optimized custom allocWithZone methods")
OPTION( PrintRawIsa,              code_PRINT_RAW_ISA,              "log classes that require raw pointer isa fields")

OPTION( DebugUnload,              code_DEBUG_UNLOAD,               "warn about poorly-behaving bundles when unloaded")
OPTION( DebugFragileSuperclasses, code_DEBUG_FRAGILE_SUPERCLASSES, "warn about subclasses that may have been broken by subsequent changes to superclasses")
OPTION( DebugFinalizers,          code_DEBUG_FINALIZERS,           "warn about classes that implement -dealloc but not -finalize")
OPTION( DebugNilSync,             code_DEBUG_NIL_SYNC,             "warn about @synchronized(nil), which does no synchronization")
OPTION( DebugNonFragileIvars,     code_DEBUG_NONFRAGILE_IVARS,     "capriciously rearrange non-fragile ivars")
OPTION( DebugAltHandlers,         code_DEBUG_ALT_HANDLERS,         "record more info about bad alt handler use")
OPTION( DebugMissingPools,        code_DEBUG_MISSING_POOLS,        "warn about autorelease with no pool in place, which may be a leak")
OPTION( DebugPoolAllocation,      code_DEBUG_POOL_ALLOCATION,      "halt when autorelease pools are popped out of order, and allow heap debuggers to track autorelease pools")
OPTION( DebugDuplicateClasses,    code_DEBUG_DUPLICATE_CLASSES,    "halt when multiple classes with the same name are present")

OPTION( DisableGC,                code_DISABLE_GC,                 "force GC OFF, even if the executable wants it on")
OPTION( DisableVtables,           code_DISABLE_VTABLES,            "disable vtable dispatch")
OPTION( DisablePreopt,            code_DISABLE_PREOPTIMIZATION,    "disable preoptimization courtesy of dyld shared cache")
OPTION( DisableTaggedPointers,    code_DISABLE_TAGGED_POINTERS,    "disable tagged pointer optimization of NSNumber et al.") 
OPTION( DisableIndexedIsa,        code_DISABLE_NONPOINTER_ISA,     "disable non-pointer isa fields")
